tenant: ali
domain: ali.zohaibofficial.online
db_name: erp_ali
replicas: 1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

image:
  repository: zohaibwarraich/erp-dummy-app # Updated to match CI/CD pipeline output
  tag: latest
  pullPolicy: IfNotPresent

database:
  image:
    repository: postgres # Separate database for each tenant
    tag: 14-alpine
  storageSize: 2Gi
