apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erp-root-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: "https://github.com/my-org/erp-gitops-config.git" # Replace with actual GitHub Repo URL
    targetRevision: HEAD
    path: tenants # Watches the entire tenants folder
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
