{{- if .Values.backup.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.tenant }}-backup-storage
  labels:
    app: {{ .Values.tenant }}-backup
spec:
  storageClassName: ebs-sc-immediate
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backup.storageSize }}
{{- end }}
