apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.tenant }}-config
data:
  TENANT_NAME: {{ .Values.tenant }}
  DATABASE_HOST: {{ .Values.tenant }}-db-svc
  DATABASE_NAME: {{ .Values.db_name }}
  APP_ENV: production
