apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tenant }}-erp
  labels:
    app: {{ .Values.tenant }}-erp
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.tenant }}-erp
  template:
    metadata:
      labels:
        app: {{ .Values.tenant }}-erp
    spec:
      containers:
        - name: erp-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.tenant }}-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.tenant }}-db-credentials
                  key: POSTGRES_PASSWORD
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
