apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.tenant }}-db-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore # Assumes a ClusterSecretStore named aws-secrets-manager exists
  target:
    name: {{ .Values.tenant }}-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: erp/tenants/{{ .Values.tenant }} # The secret name in AWS Secrets Manager
        property: POSTGRES_PASSWORD
